# Generated by Django 3.0 on 2021-05-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='CVS',
            new_name='ACS',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=40),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
